/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'admin-users': AdminUserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    programmes: Programme;
    'impact-stories': ImpactStory;
    'gallery-albums': GalleryAlbum;
    leadership: Leadership;
    testimonials: Testimonial;
    faqs: Faq;
    pages: Page;
    'reference-counters': ReferenceCounter;
    'support-applications': SupportApplication;
    beneficiaries: Beneficiary;
    'case-notes': CaseNote;
    documents: Document;
    'submission-files': SubmissionFile;
    'volunteer-applications': VolunteerApplication;
    'in-kind-offers': InKindOffer;
    'partner-enquiries': PartnerEnquiry;
    'contact-messages': ContactMessage;
    subscribers: Subscriber;
    donors: Donor;
    campaigns: Campaign;
    donations: Donation;
    'payment-transactions': PaymentTransaction;
    'webhook-events': WebhookEvent;
    'admin-users': AdminUser;
    'email-templates': EmailTemplate;
    notifications: Notification;
    redirects: Redirect;
    'activity-log': ActivityLog;
    'email-log': EmailLog;
    'audit-log': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    'impact-stories': ImpactStoriesSelect<false> | ImpactStoriesSelect<true>;
    'gallery-albums': GalleryAlbumsSelect<false> | GalleryAlbumsSelect<true>;
    leadership: LeadershipSelect<false> | LeadershipSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'reference-counters': ReferenceCountersSelect<false> | ReferenceCountersSelect<true>;
    'support-applications': SupportApplicationsSelect<false> | SupportApplicationsSelect<true>;
    beneficiaries: BeneficiariesSelect<false> | BeneficiariesSelect<true>;
    'case-notes': CaseNotesSelect<false> | CaseNotesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'submission-files': SubmissionFilesSelect<false> | SubmissionFilesSelect<true>;
    'volunteer-applications': VolunteerApplicationsSelect<false> | VolunteerApplicationsSelect<true>;
    'in-kind-offers': InKindOffersSelect<false> | InKindOffersSelect<true>;
    'partner-enquiries': PartnerEnquiriesSelect<false> | PartnerEnquiriesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    donors: DonorsSelect<false> | DonorsSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    'payment-transactions': PaymentTransactionsSelect<false> | PaymentTransactionsSelect<true>;
    'webhook-events': WebhookEventsSelect<false> | WebhookEventsSelect<true>;
    'admin-users': AdminUsersSelect<false> | AdminUsersSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'activity-log': ActivityLogSelect<false> | ActivityLogSelect<true>;
    'email-log': EmailLogSelect<false> | EmailLogSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    foundation: Foundation;
    'seo-defaults': SeoDefault;
    'statistics-manual': StatisticsManual;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    foundation: FoundationSelect<false> | FoundationSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'statistics-manual': StatisticsManualSelect<false> | StatisticsManualSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: AdminUser;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  tags?: string[] | null;
  uploadedBy?: (number | null) | AdminUser;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-users".
 */
export interface AdminUser {
  id: number;
  name: string;
  role: 'owner' | 'administrator' | 'content' | 'case' | 'finance';
  status: 'active' | 'suspended';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admin-users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  name: string;
  slug: string;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  objectives?: string[] | null;
  activities?: string[] | null;
  impact?: string | null;
  featured?: boolean | null;
  order?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stories".
 */
export interface ImpactStory {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  images?: (number | Media)[] | null;
  programme?: (number | null) | Programme;
  date?: string | null;
  location?: string | null;
  beneficiariesReached?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums".
 */
export interface GalleryAlbum {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  cover?: (number | null) | Media;
  images?: (number | Media)[] | null;
  programme?: (number | null) | Programme;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership".
 */
export interface Leadership {
  id: number;
  name: string;
  position: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  role?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  blocks?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading: string;
            body?: string | null;
            buttonLabel?: string | null;
            buttonHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reference-counters".
 */
export interface ReferenceCounter {
  id: number;
  prefix: string;
  value: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-applications".
 */
export interface SupportApplication {
  id: number;
  reference: string;
  submittedAt?: string | null;
  consentVersion?: string | null;
  consentAt?: string | null;
  sourceIpHash?: string | null;
  anonymisedAt?: string | null;
  fullName?: string | null;
  email?: string | null;
  phone?: string | null;
  supportType?: string | null;
  supportTypeOther?: string | null;
  gender?: string | null;
  dateOfBirth?: string | null;
  nationality?: string | null;
  contactMethod?: string | null;
  referralSource?: string | null;
  state?: string | null;
  lga?: string | null;
  landmark?: string | null;
  durationAtAddress?: string | null;
  housingStatus?: string | null;
  urgency?: string | null;
  appliedElsewhere?: string | null;
  occupation?: string | null;
  maritalStatus?: string | null;
  incomeSourceOther?: string | null;
  children?: string | null;
  dependents?: string | null;
  primaryProvider?: string | null;
  householdSize?: string | null;
  elderlyRelatives?: string | null;
  previousSupport?: string | null;
  address?: string | null;
  livingConditions?: string | null;
  supportSummary?: string | null;
  challenge?: string | null;
  expectedImpact?: string | null;
  previousSupportDetail?: string | null;
  stepsTaken?: string | null;
  additionalInformation?: string | null;
  declarationTrue?: string | null;
  declarationNoGuarantee?: string | null;
  declarationContact?: string | null;
  declarationDataUse?: string | null;
  status: 'new' | 'under_review' | 'approved' | 'declined' | 'support_provided' | 'closed';
  /**
   * Required to decline. Kept on the record.
   */
  declineReason?: string | null;
  assignedTo?: (number | null) | AdminUser;
  /**
   * Collected at approval, never at application (PRV-04).
   */
  nationalId?: string | null;
  monthlyIncome?: string | null;
  incomeSource?: string | null;
  situationNarrative?: string | null;
  specialNeedsDependents?: string | null;
  specialNeedsDetail?: string | null;
  housingChallenges?: string | null;
  documents?: (number | Document)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  storageKey?: string | null;
  application?: (number | null) | SupportApplication;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beneficiaries".
 */
export interface Beneficiary {
  id: number;
  fullName?: string | null;
  email?: string | null;
  phone?: string | null;
  application?: (number | null) | SupportApplication;
  programme?: string | null;
  anonymisedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-notes".
 */
export interface CaseNote {
  id: number;
  summary: string;
  body?: string | null;
  application?: (number | null) | SupportApplication;
  author?: (number | null) | AdminUser;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-files".
 */
export interface SubmissionFile {
  id: number;
  submittedWith?: string | null;
  anonymisedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-applications".
 */
export interface VolunteerApplication {
  id: number;
  reference: string;
  submittedAt?: string | null;
  consentVersion?: string | null;
  consentAt?: string | null;
  sourceIpHash?: string | null;
  anonymisedAt?: string | null;
  fullName?: string | null;
  email?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  gender?: string | null;
  dateOfBirth?: string | null;
  location?: string | null;
  occupation?: string | null;
  qualification?: string | null;
  profession?: string | null;
  volunteeredBefore?: string | null;
  areaOfInterest?: string | null;
  availability?: string | null;
  commitment?: string | null;
  consent?: string | null;
  skills?: string | null;
  previousExperience?: string | null;
  motivation?: string | null;
  status?: ('new' | 'contacted' | 'accepted' | 'declined' | 'closed') | null;
  declineReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "in-kind-offers".
 */
export interface InKindOffer {
  id: number;
  reference: string;
  submittedAt?: string | null;
  consentVersion?: string | null;
  consentAt?: string | null;
  sourceIpHash?: string | null;
  anonymisedAt?: string | null;
  fullName?: string | null;
  email?: string | null;
  phone?: string | null;
  category?: string | null;
  quantity?: string | null;
  condition?: string | null;
  location?: string | null;
  deliveryMethod?: string | null;
  contactMethod?: string | null;
  pickupDate?: string | null;
  pickupTime?: string | null;
  destination?: string | null;
  acknowledgeDonation?: string | null;
  description?: string | null;
  pickupAddress?: string | null;
  pickupInstructions?: string | null;
  photo?: (number | null) | SubmissionFile;
  /**
   * Deprecated. Removed after Phase 3.
   */
  photoKey?: string | null;
  status?: ('new' | 'accepted' | 'received' | 'declined' | 'closed') | null;
  declineReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-enquiries".
 */
export interface PartnerEnquiry {
  id: number;
  reference: string;
  submittedAt?: string | null;
  consentVersion?: string | null;
  consentAt?: string | null;
  sourceIpHash?: string | null;
  anonymisedAt?: string | null;
  organisation?: string | null;
  contactPerson?: string | null;
  location?: string | null;
  partnershipType?: string | null;
  phone?: string | null;
  consent?: string | null;
  email?: string | null;
  message?: string | null;
  status?: ('new' | 'in_discussion' | 'agreed' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  reference: string;
  submittedAt?: string | null;
  consentVersion?: string | null;
  consentAt?: string | null;
  sourceIpHash?: string | null;
  anonymisedAt?: string | null;
  name?: string | null;
  subject?: string | null;
  enquiry?: string | null;
  email?: string | null;
  message?: string | null;
  status?: ('unread' | 'read' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  status?: ('subscribed' | 'unsubscribed') | null;
  consentVersion?: string | null;
  consentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donors".
 */
export interface Donor {
  id: number;
  email: string;
  fullName?: string | null;
  phone?: string | null;
  firstGiftAt?: string | null;
  latestGiftAt?: string | null;
  anonymisedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: number;
  name: string;
  slug: string;
  /**
   * In kobo for naira and cents for dollars: ₦1,000 is 100000.
   */
  targetMinor?: number | null;
  currency?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  receiptNumber?: number | null;
  donor: number | Donor;
  campaign?: (number | null) | Campaign;
  programme?: (number | null) | Programme;
  /**
   * In kobo for naira and cents for dollars: ₦1,000 is 100000.
   */
  amountMinor: number;
  currency: string;
  status: 'successful' | 'refunded' | 'partially_refunded';
  provider: string;
  providerReference: string;
  donatedAt?: string | null;
  receiptSentAt?: string | null;
  isAnonymous?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-transactions".
 */
export interface PaymentTransaction {
  id: number;
  provider: string;
  providerReference: string;
  donation?: (number | null) | Donation;
  eventType?: string | null;
  status?: ('pending' | 'successful' | 'failed' | 'refunded') | null;
  amountMinor?: number | null;
  currency?: string | null;
  feesMinor?: number | null;
  rawPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events".
 */
export interface WebhookEvent {
  id: number;
  provider: string;
  providerEventId: string;
  signatureValid?: boolean | null;
  processedAt?: string | null;
  processingError?: string | null;
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  receivedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  name: string;
  subject: string;
  body?: string | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  message: string;
  recipient: number | AdminUser;
  href?: string | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log".
 */
export interface ActivityLog {
  id: number;
  summary: string;
  collectionName?: string | null;
  recordId?: string | null;
  fromStatus?: string | null;
  toStatus?: string | null;
  actor?: (number | null) | AdminUser;
  occurredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log".
 */
export interface EmailLog {
  id: number;
  template: string;
  recipient: string;
  providerMessageId?: string | null;
  status?: string | null;
  sentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  actor: number | AdminUser;
  action:
    | 'login'
    | 'login_failed'
    | 'view_sensitive'
    | 'create'
    | 'update'
    | 'delete'
    | 'export'
    | 'role_change'
    | 'status_change';
  collectionName?: string | null;
  recordId?: string | null;
  fieldNames?: string[] | null;
  rowCount?: number | null;
  ipHash?: string | null;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'impact-stories';
        value: number | ImpactStory;
      } | null)
    | ({
        relationTo: 'gallery-albums';
        value: number | GalleryAlbum;
      } | null)
    | ({
        relationTo: 'leadership';
        value: number | Leadership;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'reference-counters';
        value: number | ReferenceCounter;
      } | null)
    | ({
        relationTo: 'support-applications';
        value: number | SupportApplication;
      } | null)
    | ({
        relationTo: 'beneficiaries';
        value: number | Beneficiary;
      } | null)
    | ({
        relationTo: 'case-notes';
        value: number | CaseNote;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'submission-files';
        value: number | SubmissionFile;
      } | null)
    | ({
        relationTo: 'volunteer-applications';
        value: number | VolunteerApplication;
      } | null)
    | ({
        relationTo: 'in-kind-offers';
        value: number | InKindOffer;
      } | null)
    | ({
        relationTo: 'partner-enquiries';
        value: number | PartnerEnquiry;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'donors';
        value: number | Donor;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: number | Campaign;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'payment-transactions';
        value: number | PaymentTransaction;
      } | null)
    | ({
        relationTo: 'webhook-events';
        value: number | WebhookEvent;
      } | null)
    | ({
        relationTo: 'admin-users';
        value: number | AdminUser;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'activity-log';
        value: number | ActivityLog;
      } | null)
    | ({
        relationTo: 'email-log';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admin-users';
    value: number | AdminUser;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admin-users';
    value: number | AdminUser;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  tags?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  heroImage?: T;
  gallery?: T;
  objectives?: T;
  activities?: T;
  impact?: T;
  featured?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact-stories_select".
 */
export interface ImpactStoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  featuredImage?: T;
  images?: T;
  programme?: T;
  date?: T;
  location?: T;
  beneficiariesReached?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-albums_select".
 */
export interface GalleryAlbumsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  cover?: T;
  images?: T;
  programme?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership_select".
 */
export interface LeadershipSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reference-counters_select".
 */
export interface ReferenceCountersSelect<T extends boolean = true> {
  prefix?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-applications_select".
 */
export interface SupportApplicationsSelect<T extends boolean = true> {
  reference?: T;
  submittedAt?: T;
  consentVersion?: T;
  consentAt?: T;
  sourceIpHash?: T;
  anonymisedAt?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  supportType?: T;
  supportTypeOther?: T;
  gender?: T;
  dateOfBirth?: T;
  nationality?: T;
  contactMethod?: T;
  referralSource?: T;
  state?: T;
  lga?: T;
  landmark?: T;
  durationAtAddress?: T;
  housingStatus?: T;
  urgency?: T;
  appliedElsewhere?: T;
  occupation?: T;
  maritalStatus?: T;
  incomeSourceOther?: T;
  children?: T;
  dependents?: T;
  primaryProvider?: T;
  householdSize?: T;
  elderlyRelatives?: T;
  previousSupport?: T;
  address?: T;
  livingConditions?: T;
  supportSummary?: T;
  challenge?: T;
  expectedImpact?: T;
  previousSupportDetail?: T;
  stepsTaken?: T;
  additionalInformation?: T;
  declarationTrue?: T;
  declarationNoGuarantee?: T;
  declarationContact?: T;
  declarationDataUse?: T;
  status?: T;
  declineReason?: T;
  assignedTo?: T;
  nationalId?: T;
  monthlyIncome?: T;
  incomeSource?: T;
  situationNarrative?: T;
  specialNeedsDependents?: T;
  specialNeedsDetail?: T;
  housingChallenges?: T;
  documents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beneficiaries_select".
 */
export interface BeneficiariesSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  phone?: T;
  application?: T;
  programme?: T;
  anonymisedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-notes_select".
 */
export interface CaseNotesSelect<T extends boolean = true> {
  summary?: T;
  body?: T;
  application?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  storageKey?: T;
  application?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submission-files_select".
 */
export interface SubmissionFilesSelect<T extends boolean = true> {
  submittedWith?: T;
  anonymisedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteer-applications_select".
 */
export interface VolunteerApplicationsSelect<T extends boolean = true> {
  reference?: T;
  submittedAt?: T;
  consentVersion?: T;
  consentAt?: T;
  sourceIpHash?: T;
  anonymisedAt?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  gender?: T;
  dateOfBirth?: T;
  location?: T;
  occupation?: T;
  qualification?: T;
  profession?: T;
  volunteeredBefore?: T;
  areaOfInterest?: T;
  availability?: T;
  commitment?: T;
  consent?: T;
  skills?: T;
  previousExperience?: T;
  motivation?: T;
  status?: T;
  declineReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "in-kind-offers_select".
 */
export interface InKindOffersSelect<T extends boolean = true> {
  reference?: T;
  submittedAt?: T;
  consentVersion?: T;
  consentAt?: T;
  sourceIpHash?: T;
  anonymisedAt?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  category?: T;
  quantity?: T;
  condition?: T;
  location?: T;
  deliveryMethod?: T;
  contactMethod?: T;
  pickupDate?: T;
  pickupTime?: T;
  destination?: T;
  acknowledgeDonation?: T;
  description?: T;
  pickupAddress?: T;
  pickupInstructions?: T;
  photo?: T;
  photoKey?: T;
  status?: T;
  declineReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partner-enquiries_select".
 */
export interface PartnerEnquiriesSelect<T extends boolean = true> {
  reference?: T;
  submittedAt?: T;
  consentVersion?: T;
  consentAt?: T;
  sourceIpHash?: T;
  anonymisedAt?: T;
  organisation?: T;
  contactPerson?: T;
  location?: T;
  partnershipType?: T;
  phone?: T;
  consent?: T;
  email?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  reference?: T;
  submittedAt?: T;
  consentVersion?: T;
  consentAt?: T;
  sourceIpHash?: T;
  anonymisedAt?: T;
  name?: T;
  subject?: T;
  enquiry?: T;
  email?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  consentVersion?: T;
  consentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donors_select".
 */
export interface DonorsSelect<T extends boolean = true> {
  email?: T;
  fullName?: T;
  phone?: T;
  firstGiftAt?: T;
  latestGiftAt?: T;
  anonymisedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  targetMinor?: T;
  currency?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  receiptNumber?: T;
  donor?: T;
  campaign?: T;
  programme?: T;
  amountMinor?: T;
  currency?: T;
  status?: T;
  provider?: T;
  providerReference?: T;
  donatedAt?: T;
  receiptSentAt?: T;
  isAnonymous?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-transactions_select".
 */
export interface PaymentTransactionsSelect<T extends boolean = true> {
  provider?: T;
  providerReference?: T;
  donation?: T;
  eventType?: T;
  status?: T;
  amountMinor?: T;
  currency?: T;
  feesMinor?: T;
  rawPayload?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webhook-events_select".
 */
export interface WebhookEventsSelect<T extends boolean = true> {
  provider?: T;
  providerEventId?: T;
  signatureValid?: T;
  processedAt?: T;
  processingError?: T;
  payload?: T;
  receivedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-users_select".
 */
export interface AdminUsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  name?: T;
  subject?: T;
  body?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  message?: T;
  recipient?: T;
  href?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log_select".
 */
export interface ActivityLogSelect<T extends boolean = true> {
  summary?: T;
  collectionName?: T;
  recordId?: T;
  fromStatus?: T;
  toStatus?: T;
  actor?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-log_select".
 */
export interface EmailLogSelect<T extends boolean = true> {
  template?: T;
  recipient?: T;
  providerMessageId?: T;
  status?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  collectionName?: T;
  recordId?: T;
  fieldNames?: T;
  rowCount?: T;
  ipHash?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  foundationName: string;
  email?: string | null;
  phone?: string | null;
  nigeriaAddress?: string | null;
  usaAddress?: string | null;
  socials?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    tiktok?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "foundation".
 */
export interface Foundation {
  id: number;
  vision?: string | null;
  mission?: string | null;
  founderStory?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  history?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  titleTemplate?: string | null;
  description?: string | null;
  openGraphImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statistics-manual".
 */
export interface StatisticsManual {
  id: number;
  figures?:
    | {
        label: string;
        value: string;
        source: string;
        verifiedAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  foundationName?: T;
  email?: T;
  phone?: T;
  nigeriaAddress?: T;
  usaAddress?: T;
  socials?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
        linkedin?: T;
        tiktok?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "foundation_select".
 */
export interface FoundationSelect<T extends boolean = true> {
  vision?: T;
  mission?: T;
  founderStory?: T;
  history?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  titleTemplate?: T;
  description?: T;
  openGraphImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statistics-manual_select".
 */
export interface StatisticsManualSelect<T extends boolean = true> {
  figures?:
    | T
    | {
        label?: T;
        value?: T;
        source?: T;
        verifiedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}